---
# Update the OS and reboot
- name: Update the OS
  yum:
    name: "*"
    state: latest

- name: Is a reboot required?
  shell: needs-restarting -r
  register: restart
  failed_when: restart.rc > 1
- debug: var=restart.rc

- name: Reboot immediately if there was a change.
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when:
    - restart.rc == 1

- name: Wait for the reboot to complete if there was a change.
  wait_for_connection:
    connect_timeout: 1 # Maximum number of seconds to wait for a connection to happen before closing and retrying
    sleep: 5 # Number of seconds to sleep between checks
    delay: 5 # Number of seconds to wait before starting to poll
    timeout: 300 # Maximum number of seconds to wait for
  when: restart.rc == 1