---
# License server must run on rhel/centos, therefore, yum package is used
# install the repo and service
- name: Install repo
  yum_repository:
    name: pcoip
    description: pcoip yum repo
    baseurl: https://downloads.teradici.com/rhel/pcoip.repo

- name: Install the license server
  yum:
    name: pcoip-license-server
    state: latest

- name: Change default password
  shell: pcoip-set-password -p 1P@ssw0rd! # default password noted in public documentation

  # activate license service
- name: Activate license server with activation code
  shell: pcoip-activate-online-license -a {{ activation_code }} -c {{ license_count }} -p {{ password }}

  # Health checks
- name: Verify that service is running
  shell: sudo systemctl is-active flexnetls-TERADICI
  register: response

- name: Start service if its not running
  service:
    name: flextnetls-TERADICI
    state: restarted
  when: response.stdout != "active"

- name: Get this instance's public IP
  command: curl http://169.254.169.254/latest/meta-data/public-ipv4
  register: ec2_public_ip

- name: API health check
  uri:
    url: "http://{{ec2_public_ip.stdout}}:7070/api/1.0/health"

